export enum Configuration {
  // EXTERNAL_API
  EXTERNAL_API_URL = 'EXTERNAL_API_URL',
  EXTERNAL_API_PORT = 'EXTERNAL_API_PORT',

  // MYSQL
  MYSQL_HOST = 'MYSQL_HOST',
  MYSQL_PORT = 'MYSQL_PORT',
  MYSQL_USERNAME = 'MYSQL_USERNAME',
  MYSQL_PASSWORD = 'MYSQL_PASSWORD',
  MYSQL_DATABASE = 'MYSQL_DATABASE',
}
