export enum ResponseStatus {
  OK = 'OK',
  BAD_PARAMETER = 'BAD_PARAMETER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  SERVER_ERROR = 'SERVER_ERROR',
  NOT_SUBSCRIBING_PAGE = 'NOT_SUBSCRIBING_PAGE',
}
